version: 0.2
phases:
  command:
    - echo Logging into Amazon ECR..
    - aws --version
    - $(aws ecr get-login --region eu-west-2 --no-include-email)
    - REPOSITORY_URL=608970462845.dkr.ecr.eu-west-2.amazonaws.com/mydemo
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=build-S(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
 build:
  command:
    - echo Build started on 'date'
    - echo Building the Dcoker image...
    - docker build -t $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
 post_build:
  command:
    - echo Build completed on 'date'
    - echo Pushing the Docker Images..
    - docker push $REPOSITORY_URL:latest
    - docker push $REPOSITORY_URL:$IMAGE_TAG
    - echo writing images definitions file...
